server.port=${PORT:8080}

# --- PostgreSQL Database Configuration NEON CONSOLE---
# We use ${VARIABLE_NAME} so Google Cloud Run can inject the values securely
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Explicitly use the Postgres Driver
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update


# --- Performance & Connection Tuning for Cloud ---
# Neon is serverless; these settings prevent connection timeouts
spring.datasource.hikari.max-lifetime=480000
spring.datasource.hikari.maximum-pool-size=5


# TURN OFF SQL LOGGING COMPLETELY
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false


# --- PostgresSQL Database Configuration ---
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=public
#spring.datasource.username=postgres
#spring.datasource.password=root

# TURN OFF SQL LOGGING COMPLETELY
#spring.jpa.show-sql=false
#spring.jpa.properties.hibernate.format_sql=false

logging.level.org.hibernate=ERROR
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=OFF

spring.h2.console.enabled=false
spring.jpa.properties.hibernate.default_schema=public

# --- Swagger Configuration ---
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# --- Disable Spring Cloud Config ---
spring.cloud.config.enabled=false

# --- Encrypted Credentials ---
aws.access-key-id.encrypted=o84f3Ca7kKIapgrechnzMxPT3QpH2xae6iUFJfTs9QM=
aws.secret-access-key.encrypted=oIGyOabnoKh97RPO45N8LkjvQN1M2/15g++a+3mKKrWfMEVliYIbbUefJsyPl3NG
twilio.account-sid.encrypted=2zloWYqBoZl2Zeql8rRXBNSVqE28lbkw+5AXSg5v72iu9a1yPy2FjH6qYOgt6Xvt
twilio.auth-token.encrypted=GXo9SwymiyvxeVyMFSMp2/LLBMrudFaR72T3wvfrykAG29JSTtqUoEcXLSA2q4WD
# --- JWT Configuration ---
jwt.secret=bXlWZXJ5TG9uZ1NlY3JldEtleVRoYXRJc0F0TGVhc3QzMkNoYXJhY3RlcnNMb25nRm9yU2VjdXJpdHlQdXJwb3Nlcw==
jwt.expiration=86400000

# AWS Configuration
aws.region=us-east-1
aws.s3.bucket-name=peoject-nector-images
aws.cloudfront.url=https://d1vi79nbg06y15.cloudfront.net
aws.account-id=532810955716

# --- OTP Configuration ---
otp.expiry.minutes=5
otp.twilio.enabled=false


