package com.nector.userservice.common;

import lombok.Getter;

/**
 * Numeric mapping for roles and features to simplify permission management
 */
@Getter
public enum RoleFeatureMapping {

    // Role IDs (based on RoleType enum order)
    ROLE_SUPER_ADMIN(1),
    ROLE_ADMIN(2),
    ROLE_BUSINESS_DEV_MGR(3),
    ROLE_PLANT_MGR(4),
    ROLE_HR_MGR(5),
    ROLE_LOGISTICS_MGR(6),
    ROLE_ACCOUNT_MGR(7),
    ROLE_ACCOUNT_OFFICER(8),
    ROLE_ACCOUNT_EXECUTIVE(9),
    ROLE_NATIONAL_SALES_MGR(10),
    ROLE_STATE_SALES_MGR(11),
    ROLE_ZONAL_SALES_MGR(12),
    ROLE_REGIONAL_SALES_MGR(13),
    ROLE_AREA_SALES_MGR(14),
    ROLE_SALES_OFFICER(15),
    ROLE_SALES_EXECUTIVE(16),
    ROLE_LOGISTICS_OFFICER(17),
    ROLE_DISPATCH(18),
    ROLE_HR_EXECUTIVE(19),
    ROLE_PLANT_OFFICER(20),
    ROLE_PLANT_EXECUTIVE(21),
    ROLE_DISTRIBUTOR(22),

    // Feature IDs (based on Features enum order)
    FEATURE_DASHBOARD(1),
    FEATURE_ACCOUNTS(2),
    FEATURE_HR(3),
    FEATURE_DISTRIBUTOR(4),
    FEATURE_INVENTORY(5),
    FEATURE_SALES(6),
    FEATURE_REPORTS(7),
    FEATURE_COMPLAINT(8),
    FEATURE_PRODUCTS(9),
    FEATURE_ORDER_DETAILS(10),
    FEATURE_LOGISTIC(11),
    FEATURE_USER_RIGHTS(12),
    FEATURE_DISPATCH(13),
    FEATURE_PRODUCTS_FINISHED_PRODUCTS(14),
    FEATURE_PRODUCTS_RAW_MATERIALS(15),
    FEATURE_PRODUCTS_MACHINE_PARTS(16),
    FEATURE_INVENTORY_MASTERS(17),
    FEATURE_INVENTORY_TRANSACTIONS(18),
    FEATURE_INVENTORY_TRANSACTIONS_PROFORMA_INVOICE(19),
    FEATURE_INVENTORY_TRANSACTIONS_PO_DEPOSIT_RECEIPTS_LIST(20),
    FEATURE_INVENTORY_TRANSACTIONS_PO_LIST(21),
    FEATURE_INVENTORY_TRANSACTIONS_OUTWARD_CHALLAN(22),
    FEATURE_INVENTORY_TRANSACTIONS_SALE_INVOICE(23),
    FEATURE_INVENTORY_INWARD(24),
    FEATURE_INVENTORY_OUTWARD(25),
    FEATURE_TRANSACTION_CASHBOOK(26),
    FEATURE_TRANSACTION_MASTER(27),
    FEATURE_ADMIN_APPROVAL(28);

    private final int id;

    RoleFeatureMapping(int id) {
        this.id = id;
    }

    public static int getRoleId(RoleType roleType) {
        return switch (roleType) {
            case SUPER_ADMIN -> ROLE_SUPER_ADMIN.getId();
            case ADMIN -> ROLE_ADMIN.getId();
            case BUSINESS_DEV_MGR -> ROLE_BUSINESS_DEV_MGR.getId();
            case PLANT_MGR -> ROLE_PLANT_MGR.getId();
            case HR_MGR -> ROLE_HR_MGR.getId();
            case LOGISTICS_MGR -> ROLE_LOGISTICS_MGR.getId();
            case ACCOUNT_MGR -> ROLE_ACCOUNT_MGR.getId();
            case ACCOUNT_OFFICER -> ROLE_ACCOUNT_OFFICER.getId();
            case ACCOUNT_EXECUTIVE -> ROLE_ACCOUNT_EXECUTIVE.getId();
            case NATIONAL_SALES_MGR -> ROLE_NATIONAL_SALES_MGR.getId();
            case STATE_SALES_MGR -> ROLE_STATE_SALES_MGR.getId();
            case ZONAL_SALES_MGR -> ROLE_ZONAL_SALES_MGR.getId();
            case REGIONAL_SALES_MGR -> ROLE_REGIONAL_SALES_MGR.getId();
            case AREA_SALES_MGR -> ROLE_AREA_SALES_MGR.getId();
            case SALES_OFFICER -> ROLE_SALES_OFFICER.getId();
            case SALES_EXECUTIVE -> ROLE_SALES_EXECUTIVE.getId();
            case LOGISTICS_OFFICER -> ROLE_LOGISTICS_OFFICER.getId();
            case DISPATCH -> ROLE_DISPATCH.getId();
            case HR_EXECUTIVE -> ROLE_HR_EXECUTIVE.getId();
            case PLANT_OFFICER -> ROLE_PLANT_OFFICER.getId();
            case PLANT_EXECUTIVE -> ROLE_PLANT_EXECUTIVE.getId();
            case Distributor -> ROLE_DISTRIBUTOR.getId();
        };
    }

    public static int getFeatureId(com.nector.userservice.common.features.Features feature) {
        return switch (feature) {
            case DASHBOARD -> FEATURE_DASHBOARD.getId();
            case ACCOUNTS -> FEATURE_ACCOUNTS.getId();
            case HR -> FEATURE_HR.getId();
            case DISTRIBUTOR -> FEATURE_DISTRIBUTOR.getId();
            case INVENTORY -> FEATURE_INVENTORY.getId();
            case SALES -> FEATURE_SALES.getId();
            case REPORTS -> FEATURE_REPORTS.getId();
            case COMPLAINT -> FEATURE_COMPLAINT.getId();
            case PRODUCTS -> FEATURE_PRODUCTS.getId();
            case ORDER_DETAILS -> FEATURE_ORDER_DETAILS.getId();
            case LOGISTIC -> FEATURE_LOGISTIC.getId();
            case USER_RIGHTS -> FEATURE_USER_RIGHTS.getId();
            case DISPATCH -> FEATURE_DISPATCH.getId();
            case PRODUCTS_FINISHED_PRODUCTS -> FEATURE_PRODUCTS_FINISHED_PRODUCTS.getId();
            case PRODUCTS_RAW_MATERIALS -> FEATURE_PRODUCTS_RAW_MATERIALS.getId();
            case PRODUCTS_MACHINE_PARTS -> FEATURE_PRODUCTS_MACHINE_PARTS.getId();
            case INVENTORY_MASTERS -> FEATURE_INVENTORY_MASTERS.getId();
            case INVENTORY_TRANSACTIONS -> FEATURE_INVENTORY_TRANSACTIONS.getId();
            case INVENTORY_TRANSACTIONS_PROFORMA_INVOICE -> FEATURE_INVENTORY_TRANSACTIONS_PROFORMA_INVOICE.getId();
            case INVENTORY_TRANSACTIONS_PO_DEPOSIT_RECEIPTS_LIST -> FEATURE_INVENTORY_TRANSACTIONS_PO_DEPOSIT_RECEIPTS_LIST.getId();
            case INVENTORY_TRANSACTIONS_PO_LIST -> FEATURE_INVENTORY_TRANSACTIONS_PO_LIST.getId();
            case INVENTORY_TRANSACTIONS_OUTWARD_CHALLAN -> FEATURE_INVENTORY_TRANSACTIONS_OUTWARD_CHALLAN.getId();
            case INVENTORY_TRANSACTIONS_SALE_INVOICE -> FEATURE_INVENTORY_TRANSACTIONS_SALE_INVOICE.getId();
            case INVENTORY_INWARD -> FEATURE_INVENTORY_INWARD.getId();
            case INVENTORY_OUTWARD -> FEATURE_INVENTORY_OUTWARD.getId();
            case TRANSACTION_CASHBOOK -> FEATURE_TRANSACTION_CASHBOOK.getId();
            case TRANSACTION_MASTER -> FEATURE_TRANSACTION_MASTER.getId();
            case ADMIN_APPROVAL -> FEATURE_ADMIN_APPROVAL.getId();
        };
    }
}
