package com.nector.userservice.common;

import lombok.Getter;

@Getter
public enum RoleFeatureMapping {

    // Feature IDs (based on Features enum order)
    FEATURE_DASHBOARD(1),
    FEATURE_ACCOUNTS(2),
    FEATURE_HR(3),
    FEATURE_DISTRIBUTOR(4),
    FEATURE_INVENTORY(5),
    FEATURE_SALES(6),
    FEATURE_REPORTING_MANAGER(7),
    FEATURE_COMPLAINT(8),
    FEATURE_PRODUCTS(9),
    FEATURE_ORDER_DETAILS(10),
    FEATURE_LOGISTIC(11),
    FEATURE_USER_RIGHTS(12),
    FEATURE_DISPATCH(13),
    FEATURE_PRODUCTS_FINISHED_PRODUCTS(14),
    FEATURE_PRODUCTS_RAW_MATERIALS(15),
    FEATURE_PRODUCTS_MACHINE_PARTS(16),
    FEATURE_INVENTORY_MASTERS(17),
    FEATURE_INVENTORY_TRANSACTIONS(18),
    FEATURE_INVENTORY_TRANSACTIONS_PROFORMA_INVOICE(19),
    FEATURE_INVENTORY_TRANSACTIONS_PO_DEPOSIT_RECEIPTS_LIST(20),
    FEATURE_INVENTORY_TRANSACTIONS_PO_LIST(21),
    FEATURE_INVENTORY_TRANSACTIONS_OUTWARD_CHALLAN(22),
    FEATURE_INVENTORY_TRANSACTIONS_SALE_INVOICE(23),
    FEATURE_INVENTORY_INWARD(24),
    FEATURE_INVENTORY_OUTWARD(25),
    FEATURE_TRANSACTION_CASHBOOK(26),
    FEATURE_TRANSACTION_MASTER(27),
    FEATURE_ADMIN_APPROVAL(28),
    FEATURE_ACCOUNTS_MASTER(29),
    FEATURE_ACCOUNTS_PAYMENT_REQUESTS(30),
    FEATURE_ACCOUNTS_PI_UPDATE(31),
    FEATURE_HR_KRA_KPI(32),
    FEATURE_COMPLAINTS_MANAGEMENT(33),
    FEATURE_REPORTS(34),
    FEATURE_REPORT_MIS_DASHBOARD(35),
    FEATURE_REPORT_INVENTORY(36),
    FEATURE_REPORT_STOCK_MOVEMENT(37),
    FEATURE_REPORT_BATCH_MANAGEMENT(38),
    FEATURE_REPORT_PRODUCTION(39),
    FEATURE_REPORT_SALES(40),
    FEATURE_REPORT_RECEIVABLES(41),
    FEATURE_REPORT_SALES_ORDERS(42),
    FEATURE_REPORT_DISPATCH(43),
    FEATURE_REPORT_INVENTORY_ISSUES(44),
    FEATURE_REPORT_SCRAP(45);

    private final int id;

    RoleFeatureMapping(int id) {
        this.id = id;
    }

    public static int getFeatureId(com.nector.userservice.common.features.Features feature) {
        return switch (feature) {
            case DASHBOARD -> FEATURE_DASHBOARD.getId();
            case ACCOUNTS -> FEATURE_ACCOUNTS.getId();
            case HR -> FEATURE_HR.getId();
            case DISTRIBUTOR -> FEATURE_DISTRIBUTOR.getId();
            case INVENTORY -> FEATURE_INVENTORY.getId();
            case SALES -> FEATURE_SALES.getId();
            case REPORTING_MANAGER -> FEATURE_REPORTING_MANAGER.getId();
            case COMPLAINT -> FEATURE_COMPLAINT.getId();
            case PRODUCTS -> FEATURE_PRODUCTS.getId();
            case ORDER_DETAILS -> FEATURE_ORDER_DETAILS.getId();
            case LOGISTIC -> FEATURE_LOGISTIC.getId();
            case USER_RIGHTS -> FEATURE_USER_RIGHTS.getId();
            case DISPATCH -> FEATURE_DISPATCH.getId();
            case PRODUCTS_FINISHED_PRODUCTS -> FEATURE_PRODUCTS_FINISHED_PRODUCTS.getId();
            case PRODUCTS_RAW_MATERIALS -> FEATURE_PRODUCTS_RAW_MATERIALS.getId();
            case PRODUCTS_MACHINE_PARTS -> FEATURE_PRODUCTS_MACHINE_PARTS.getId();
            case INVENTORY_MASTERS -> FEATURE_INVENTORY_MASTERS.getId();
            case INVENTORY_TRANSACTIONS -> FEATURE_INVENTORY_TRANSACTIONS.getId();
            case INVENTORY_TRANSACTIONS_PROFORMA_INVOICE -> FEATURE_INVENTORY_TRANSACTIONS_PROFORMA_INVOICE.getId();
            case INVENTORY_TRANSACTIONS_PO_DEPOSIT_RECEIPTS_LIST -> FEATURE_INVENTORY_TRANSACTIONS_PO_DEPOSIT_RECEIPTS_LIST.getId();
            case INVENTORY_TRANSACTIONS_PO_LIST -> FEATURE_INVENTORY_TRANSACTIONS_PO_LIST.getId();
            case INVENTORY_TRANSACTIONS_OUTWARD_CHALLAN -> FEATURE_INVENTORY_TRANSACTIONS_OUTWARD_CHALLAN.getId();
            case INVENTORY_TRANSACTIONS_SALE_INVOICE -> FEATURE_INVENTORY_TRANSACTIONS_SALE_INVOICE.getId();
            case INVENTORY_INWARD -> FEATURE_INVENTORY_INWARD.getId();
            case INVENTORY_OUTWARD -> FEATURE_INVENTORY_OUTWARD.getId();
            case TRANSACTION_CASHBOOK -> FEATURE_TRANSACTION_CASHBOOK.getId();
            case TRANSACTION_MASTER -> FEATURE_TRANSACTION_MASTER.getId();
            case ADMIN_APPROVAL -> FEATURE_ADMIN_APPROVAL.getId();
            case ACCOUNTS_MASTER -> FEATURE_ACCOUNTS_MASTER.getId();
            case ACCOUNTS_PAYMENT_REQUESTS -> FEATURE_ACCOUNTS_PAYMENT_REQUESTS.getId();
            case ACCOUNTS_PI_UPDATE -> FEATURE_ACCOUNTS_PI_UPDATE.getId();
            case HR_KRA_KPI -> FEATURE_HR_KRA_KPI.getId();
            case COMPLAINTS_MANAGEMENT -> FEATURE_COMPLAINTS_MANAGEMENT.getId();
            case REPORTS -> FEATURE_REPORTS.getId();
            case REPORT_MIS_DASHBOARD -> FEATURE_REPORT_MIS_DASHBOARD.getId();
            case REPORT_INVENTORY -> FEATURE_REPORT_INVENTORY.getId();
            case REPORT_STOCK_MOVEMENT -> FEATURE_REPORT_STOCK_MOVEMENT.getId();
            case REPORT_BATCH_MANAGEMENT -> FEATURE_REPORT_BATCH_MANAGEMENT.getId();
            case REPORT_PRODUCTION -> FEATURE_REPORT_PRODUCTION.getId();
            case REPORT_SALES -> FEATURE_REPORT_SALES.getId();
            case REPORT_RECEIVABLES -> FEATURE_REPORT_RECEIVABLES.getId();
            case REPORT_SALES_ORDERS -> FEATURE_REPORT_SALES_ORDERS.getId();
            case REPORT_DISPATCH -> FEATURE_REPORT_DISPATCH.getId();
            case REPORT_INVENTORY_ISSUES -> FEATURE_REPORT_INVENTORY_ISSUES.getId();
            case REPORT_SCRAP -> FEATURE_REPORT_SCRAP.getId();
        };
    }
}
